### ISSUE TITLE
[Feature] payment original record add 기능 추가

### ISSUE THREAD

**Issue by heechul90** [woorinpang/settlement-service#85]
# Description 
- 결제 원본기록 add 기능 추가하기

# Todos
- [x] settlement-api POST /api/v1/payment/original/records/{transactionId} 추가
- [x] settlement-api POST /api/v1/payment/original/records/{transactionId} 테스트 추가
- [x] domain:payment-domain 결제원본기록 add 추가
- [x] domain:payment-domain 결제원본기록 add test 추가
- [x] storage:main-db 결제원본기록 add 추가
- [x] storage:main-db 결제원본기록 add test 추가
